name: Java Test CI

on:
  push:
    branches: [ main, sandbox ]
  pull_request:
    branches: [ main, sandbox ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o JDK (pode ser 17, 19, etc.)
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19

      # Cache do Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Compila e roda os testes com cobertura (gera target/site/jacoco)
      - name: Build and test with JaCoCo
        run: mvn clean verify

      # (Opcional) Exibir resumo dos testes no log
      - name: Show test results
        if: always()
        run: cat target/surefire-reports/*.txt || echo "No test reports found"

      # 6(Opcional) Análise no SonarCloud
      - name: SonarCloud Scan (via Maven)
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=gchavess_ziro-backend \
          -Dsonar.organization=gchavess \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
